name: Scrape Offers Data

on:
  schedule:
    # Körs varje måndag kl 06:00 UTC (08:00 svensk tid)
    - cron: '0 6 * * 1'
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Ger boten tillåtelse att spara/pusha data.json

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'

      - name: Run Scraper Script
        run: node fetch-data.js

      - name: Commit and Push updated data.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update data.json" && git push)
          
